#!/bin/bash

################################################################
#install prereqisits
sudo apt-get install debootstrap xserver-xephyr schroot 

################################################################
#patch debootstrap, to allow install of ubuntu 12
sudo ln -s -T gusty /usr/share/debootstrap/scripts/precise

################################################################
#install ubuntu 12 into a subdirectory

sudo mkdir /opt/ubuntu-root
sudo /usr/sbin/debootstrap --arch i386 precise /opt/ubuntu-root http://archive.ubuntu.com/ubuntu

################################################################
#configure schroot

cat <<EOF | sudo tee -a /etc/schroot/schroot.conf >> /dev/null
[ubuntu]
description=Ubuntu
type=directory
directory=/opt/ubuntu-root
users=$USERNAME,david
groups=
root-users=$USERNAME
root-groups=
aliases=
EOF

################################################################
#configure ubuntu, to allow install from backport

cat <<EOF | sudo tee /opt/ubuntu-root/etc/apt/preferences.d/my-preferences >/dev/null
Package: *
Pin: release a=precise-backports
Pin-Priority: 100
EOF

cat <<EOF | sudo tee /opt/ubuntu-root/etc/apt/sources.list.d/my.list >/dev/null
deb http://archive.ubuntu.com/ubuntu precise main universe
deb http://archive.ubuntu.com/ubuntu precise-backports main restricted universe multiverse
EOF

sudo rm /opt/ubuntu-root/etc/apt/sources.list

schroot -u root -c ubuntu -d / -- apt-get update

################################################################
#install scratch in ubuntu directory

schroot -u root -c ubuntu -d / -- apt-get install scratch









